apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: devops
  source:
    repoURL: 'https://github.com/prajeshgitre/devops-task.git'
    targetRevision: main
    path: 'k8s/deployment'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - PruneLast=true
      - PrunePropagationPolicy=foreground
